apiVersion: v1
kind: Service
metadata:
  name: rules
  namespace: global-bank
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: rules
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rules
  namespace: global-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rules
  template:
    metadata:
      labels:
        app: rules
    spec:
      containers:
      - image: localhost:32000/brainupgrade/global-bank-rules:1.0.0
        name: rules
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
          - name: java.security.egd
            value: file:/dev/./urandom
          - name: server.port
            value: "80"
          - name: feign.url-account-service
            value: "account.global-bank.svc.cluster.local/account"
          - name: feign.url-auth-service
            value: "authentication.global-bank.svc.cluster.local/auth-ms"
